### ISSUE TITLE
popup window not show up

### ISSUE THREAD

**Issue by YuFei29** [enricozb/popup.kak#3] opened 2023-07-10 11:56 UTC
I installed kak-popup and add "evaluate-commands %sh{kak-popup init}" to kakrc according readme, but when i "popup fish", the popup window does not show up and there's nothing in *debug* buffer.

I also tried HEAD version kakoune and kak-popup, popup window also does not show up.

Is there anything I missed?

<img width="393" alt="Screenshot 2023-07-10 at 19 50 55" src="https://github.com/enricozb/popup.kak/assets/125109356/3192957c-0620-4d47-8809-661127c8ec1f">

**Comment by enricozb** [comment] 2023-07-11 04:44
How did you install popup.kak

**Comment by YuFei29** [comment] 2023-07-11 05:07
I have tried both manual and via pulgin manager [bundle](https://github.com/jdugan6240/kak-bundle)
```
# manual installed inside kitty terminal
cargo install kak-popup
# and add line  "evaluate-commands %sh{kak-popup init}" to kakrc
```

```
# via package manager
bundle popup.kak https://github.com/enricozb/popup.kak.git %{
    source "${kak_opt_bundle_path}/popup.kak/rc/popup.kak"
} %{
    cargo install --force --locked --path .
}
```

I also tried my configuration in my opensuse virtual machine. When popup for the first time, the popup window flashed (appeared but disappeared soon), and when I tried again later, the window never appeared or flashed again.

**Comment by enricozb** [comment] 2023-07-13 16:45
Ok I'm going to ask you to help me debug this issue since I don't have a mac. Here are the testing instructions:

1. Start a kakoune instance with no source files:
   ```
   kak -n
   ```
2. Initialize `popup.kak` inside that kakoune session:
   ```
   :evaluate-commands %sh{kak-popup init}
   ```
3. Get the current kakoune session, client, and window size:
   ```
   :echo %val{session} %val{client} %val{window_height} %val{window_width}
   ```
4. Then, in a _separate terminal_, use those values to start a `kak-popup` instance in debug mode:
   ```
   kak-popup popup --debug \
     --kak-session <session> \
     --kak-client <client> \
     --height <height> \
     --width <width> \
     fish
   ```

If nothing appears on the kakoune side, please tell me if there is anything in the `*debug*` buffer. Additionally, please tell me what the output of the `kak-popup` command is.

**Comment by YuFei29** [comment] 2023-07-13 17:16
**here is what I get**
```
kakoune::debug: waiting for quit
kakoune::debug: refresh::step: tmux display exited with non-zero status: exit status: 1
kakoune::debug: done waiting
kakoune::debug: failed to kill tmux session 1689268367728914000: tmux kill-session exited with non-zero status: exit status: 1
kakoune::debug: keys::step: quitting
kakoune::debug: exiting popup
kakoune::debug: error: Capture::handle_output

Caused by:
    0: status
    1: No such file or directory (os error 2)
```
**I have tried again and again, sometimes I get this**
```
kakoune::debug: waiting for quit
kakoune::debug: refresh::step: expected value at line 3 column 22
kakoune::debug: done waiting
kakoune::debug: failed to kill tmux session 1689269259204322000: tmux kill-session exited with non-zero status: exit status: 1
kakoune::debug: exiting popup
kakoune::debug: error: Capture::handle_output

Caused by:
    0: status
    1: No such file or directory (os error 2)
```

<img width="929" alt="Screenshot 2023-07-14 at 01 12 03" src="https://github.com/enricozb/popup.kak/assets/125109356/3feed045-a054-4340-a8b1-94e2ec7c2977">
<img width="929" alt="Screenshot 2023-07-14 at 01 12 05" src="https://github.com/enricozb/popup.kak/assets/125109356/7028a38f-6789-4d33-b27b-15cfec9529e5">

sometimes output are **different**
<img width="929" alt="Screenshot 2023-07-14 at 01 28 00" src="https://github.com/enricozb/popup.kak/assets/125109356/6d3e6449-595f-48b3-8e1f-2c0a5fc1d301">


I have tried in my **openSUSE virtual machine**, get the same
<img width="1920" alt="Screenshot 2023-07-14 at 01 34 19" src="https://github.com/enricozb/popup.kak/assets/125109356/8b2707e0-bcc3-4c15-8b49-bd69d5aedc49">

**Comment by enricozb** [comment] 2023-07-14 07:50
Do you have a non-default tmux configuration? If so this could be the cause. It's on my TODO list to have popup.kak spin up tmux sessions that don't use the user's configuration, but instead just a default one.

**Comment by YuFei29** [comment] 2023-07-14 07:51
> 

I have no tmux config file, I just installed tmux

**Comment by enricozb** [comment] 2023-07-14 07:54
What's the output of the following commands:
```
tmux new-session -s testing -x 50 -y 50 -d fish
tmux resize-window -t testing -x 40 -y 10
tmux capture-pane -t testing -p -e
tmux kill-session -t testing
```
A screenshot is fine.

**Comment by YuFei29** [comment] 2023-07-14 07:57
> 

<img width="1236" alt="Screenshot 2023-07-14 at 15 56 43" src="https://github.com/enricozb/popup.kak/assets/125109356/431b86f9-6e8f-45ab-a404-b9be5dbe36fb">

**Comment by enricozb** [comment] 2023-07-14 07:57
can you please run them separately instead of all at once, though I think I was expecting an error anyways...

**Comment by YuFei29** [comment] 2023-07-14 08:00
> can you please run them separately instead of all at once, though I think I was expecting an error anyways...

I quit it completely and reopen a new window, it's just nothing...
I have tried macos's default Terminal.app, just the same.
<img width="830" alt="Screenshot 2023-07-14 at 16 00 20" src="https://github.com/enricozb/popup.kak/assets/125109356/405c0d82-424c-4f03-80d4-9c92c880abe7">

**Comment by enricozb** [comment] 2023-07-14 08:02
Sorry I meant like, instead of running all of the commands in a single interaction with the fish prompt, run them one by one, like this:
![image](https://github.com/enricozb/popup.kak/assets/5505315/692179de-d551-4395-a88d-dd1b3a0c6010)

**Comment by YuFei29** [comment] 2023-07-14 08:03
<img width="1236" alt="Screenshot 2023-07-14 at 16 03 22" src="https://github.com/enricozb/popup.kak/assets/125109356/80924ee0-5ffb-4547-9a18-89bfbee8c9bd">

**Comment by enricozb** [comment] 2023-07-14 08:04
Sigh, okay. Give me a bit to try reproducing this on an OpenSUSE VM, since I can do that.

**Comment by enricozb** [comment] 2023-07-14 18:31
How did you install Kakoune and tmux on OpenSUSE? I'm not familiar with this distro so I'm not sure which package managers are available.

**Comment by enricozb** [comment] 2023-07-14 18:57
While I'm waiting for your instructions on installing the deps on OpenSUSE, I tried it on an Arch Docker image and it worked fine:
```sh
docker run -it archlinux
# in docker container...

pacman -Sy kakoune tmux rust git
cargo install kak-popup

mkdir -p ~/.config/kak/autoload
git clone https://github.com/enricozb/popup.kak ~/.config/kak/autoload/popup.kak

export PATH=$PATH:~/.cargo/bin

kak
```
then doing `:popup bash` works as expected:
![image](https://github.com/enricozb/popup.kak/assets/5505315/fff39c7d-1507-4eba-8b87-eabb3488a3c4)

**Comment by enricozb** [comment] 2023-07-14 21:01
Ok I've pushed a new version of `kak-popup`, version [`v0.4.0`](https://crates.io/crates/kak-popup/0.4.0), if you can install that and rerun the debug commands from [this answer](https://github.com/enricozb/popup.kak/issues/3#issuecomment-1634615914), that would be awesome. I've added a small snippet for hopefully a better debug output.

**Comment by YuFei29** [comment] 2023-07-15 00:40
> How did you install Kakoune and tmux on OpenSUSE? I'm not familiar with this distro so I'm not sure which package managers are available.

sorry for my delayed reply, you can install package with [zypper](https://en.opensuse.org/SDB:Zypper_usage)
```
zypper install package
zypper in package # they are the same
```

**Comment by YuFei29** [comment] 2023-07-15 00:49
> While I'm waiting for your instructions on installing the deps on OpenSUSE, I tried it on an Arch Docker image and it worked fine:
> 
> ```shell
> docker run -it archlinux
> # in docker container...
> 
> pacman -Sy kakoune tmux rust git
> cargo install kak-popup
> 
> mkdir -p ~/.config/kak/autoload
> git clone https://github.com/enricozb/popup.kak ~/.config/kak/autoload/popup.kak
> 
> export PATH=$PATH:~/.cargo/bin
> 
> kak
> ```
> 
> then doing `:popup bash` works as expected: ![image](https://user-images.githubusercontent.com/5505315/253653954-fff39c7d-1507-4eba-8b87-eabb3488a3c4.png)

I have tried what you did, it works for me, I can see popup window show up and work. So I tried this on opensuse, but popup does not show up. 
Here are what I did
```bash
docker run -it opensuse/tumbleweed

zypper in kakoune tmux git
zypper in rustup
rustup install stable
cargo install kak-popup

mkdir -p ~/.config/kak/autoload
git clone https://github.com/enricozb/popup.kak ~/.config/kak/autoload/popup.kak

export PATH=$PATH:/root/.cargo/bin

kak
```

**Comment by YuFei29** [comment] 2023-07-15 01:03
> Ok I've pushed a new version of `kak-popup`, version [`v0.4.0`](https://crates.io/crates/kak-popup/0.4.0), if you can install that and rerun the debug commands from [this answer](https://github.com/enricozb/popup.kak/issues/3#issuecomment-1634615914), that would be awesome. I've added a small snippet for hopefully a better debug output.

What I get
```
kakoune::debug: waiting for quit
kakoune::debug: refresh::step: tmux display exited with non-zero status: exit status: 1, err: server exited unexpectedly

kakoune::debug: done waiting
kakoune::debug: failed to kill tmux session 1689382883470019000: tmux kill-session exited with non-zero status: exit status: 1, err: no server running on /private/tmp/tmux-501/default

kakoune::debug: exiting popup
kakoune::debug: error: Capture::handle_output

Caused by:
    0: status
    1: No such file or directory (os error 2)
```
<img width="1279" alt="Screenshot 2023-07-15 at 09 01 27" src="https://github.com/enricozb/popup.kak/assets/125109356/95f4a00d-5c94-4593-aebd-6ca1f1ea9778">
<img width="1279" alt="Screenshot 2023-07-15 at 09 01 34" src="https://github.com/enricozb/popup.kak/assets/125109356/da587729-657a-4aa0-a2b9-99b59238a2b0">

**Comment by YuFei29** [comment] 2023-07-15 01:21
> Ok I've pushed a new version of `kak-popup`, version [`v0.4.0`](https://crates.io/crates/kak-popup/0.4.0), if you can install that and rerun the debug commands from [this answer](https://github.com/enricozb/popup.kak/issues/3#issuecomment-1634615914), that would be awesome. I've added a small snippet for hopefully a better debug output.

what i get on opensuse
```
kakoune::debug: waiting for quit
kakoune::debug: refresh::step: tmux display exited with non-zero status: exit status: 1, err: no server running on /run/tmux/1000/default

kakoune::debug: done waiting
kakoune::debug: failed to kill tmux session 1689383666212399377: tmux kill-session exited with non-zero status: exit status: 1, err: no server running on /run/tmux/1000/default

kakoune::debug: exiting popup
kakoune::debug: keys::step: tmux send-keys exited with non-zero status: exit status: 1, err: no server running on /run/tmux/1000/default

kakoune::debug: error: Capture::handle_output

Caused by:
    0: status
    1: No such file or directory (os error 2)

```
<img width="1920" alt="Screenshot 2023-07-15 at 09 14 56" src="https://github.com/enricozb/popup.kak/assets/125109356/35d1b3c0-8b0c-4997-b7e6-3addac068425">

**Comment by enricozb** [comment] 2023-07-15 01:59
Ok I think we're getting to the root of the error here. I'll try the opensuse docker image, should make debugging and iteration easier. Thanks a ton for the info.

**Comment by enricozb** [comment] 2023-07-15 07:28
Okay got it working on OpenSUSE:
![image](https://github.com/enricozb/popup.kak/assets/5505315/7a361e8a-0e3f-4534-b8da-e11c754149b5)

Please test out the new version [`v0.4.1`](https://crates.io/crates/kak-popup/0.4.1).

Additionally on OpenSUSE, I wasn't able to start tmux out of the box. This happened:
```
5b560f959751:/ # tmux new-session -s kakoune kak
couldn't create directory /run/tmux/0 (No such file or directory)
``` 
so I had to run `mkdir -p /run/tmux`. Not sure why that's needed...

Lastly, I don't think this is the same issue on macOS, but we'll see.

**Comment by YuFei29** [comment] 2023-07-18 03:57
I have tested on OpenSUSE, it works when you are root user but not work for normal user. Not work on macOS.

**Comment by enricozb** [comment] 2023-10-24 21:06
Sorry for the hiatus. In response to https://github.com/enricozb/popup.kak/issues/4 I've made some changes that might fix your issue. Can you please try [`v0.5.1`](https://crates.io/crates/kak-popup/0.5.1)

**Comment by Song-Tianxiang** [comment] 2024-03-09 14:06
Works for me! I'm the author open this issue and I lost my email. You can close this issue now. Thanks for your work.

EDIT. I found debug message "popup-handle-output: on_err=dismiss status=0" in debug buffer, Is it done intentionally

**Comment by enricozb** [comment] 2024-03-09 18:06
> Works for me! I'm the author open this issue and I lost my email. You can close this issue now. Thanks for your work.
> 
> EDIT. I found debug message "popup-handle-output: on_err=dismiss status=0" in debug buffer, Is it done intentionally

Yes this is intentional, it happens when a popup closes.

**Closed as completed** 2024-04-03 01:44 UTC
